function [ net ] = createNNModel(sim_y, sim_u)
%createNNModel vyrobi dynamicky neuronovy model soustavy
% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by NFTOOL
% Created Tue May 14 13:20:40 CEST 2013
%
% This script assumes these variables are defined:
%
%   inputs - input data.
%   targets - target data.

    %creates inputs
    inputs = [sim_y(1:end-2); sim_y(2:end-1); sim_u(1:end-2); sim_u(2:end-1)];
    %creates targets
    targets = sim_y(3:end);


    % Create a Fitting Network
    hiddenLayerSize = 20;
    net = fitnet(hiddenLayerSize);


    % Setup Division of Data for Training, Validation, Testing
    net.divideParam.trainRatio = 75/100;
    net.divideParam.valRatio = 10/100;
    net.divideParam.testRatio = 15/100;


    % Train the Network
    [net,tr] = train(net,inputs,targets);

    % Test the Network
%     outputs = net(inputs);
%     errors = gsubtract(targets,outputs);
%     performance = perform(net,targets,outputs);

    % View the Network
%     view(net)

    % Plots
    % Uncomment these lines to enable various plots.
%     figure, plotperform(tr)
    %figure, plottrainstate(tr)
    %figure, plotfit(net,inputs,targets)
%     figure, plotregression(targets,outputs)
%     figure, ploterrhist(errors)
end

